### ISSUE TITLE
Latest commit fails to build on node 0.12.6

### ISSUE THREAD

**Issue by MartijnR** [albanm/node-libxslt#15]
No problem building v0.4.1 but when trying to build the latest commit ab9fec24c25a6a36b5dcb23a805879f13358521f to avoid the segfault issue, I'm getting a `make:  No rule to make target` error.

```
make: Leaving directory `/vagrant/node_modules/libxslt/node_modules/libxmljs/build'

> libxslt@0.4.1 install /vagrant/node_modules/libxslt
> node-gyp rebuild

make: Entering directory `/vagrant/node_modules/libxslt/build'
make: *** No rule to make target `Release/obj.target/libexslt/deps/libxslt/libexslt/common.o', needed by `Release/obj.target/deps/exslt.a'.  Stop.
make: Leaving directory `/vagrant/node_modules/libxslt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
```

I see the Travis build passed (on node 0.12.5). 

My npm version is v2.11.2 and I've [updated npm's internal node-gyp module](https://github.com/TooTallNate/node-gyp/wiki/Updating-npm's-bundled-node-gyp).

Any idea on what the issue could be?

**Comment by i-like-robots** [comment]
Suffering the same issue, Node 0.12.5 and NPM 2.12.1 (node-gyp 2.0.1)

**Comment by MartijnR** [comment]
A Vagrantfile to reproduce: https://gist.github.com/MartijnR/1d8eb935acf5b2fc5b9a

**Comment by albanm** [comment]
I just published to npm a 0.5.0 version.

I am not very happy releasing a version that uses a git link to a fork of libxmljs. But I feel I don't have the choice as the submodule deps/libxslt makes it more difficult to install node-libxslt from git.

Let me know if this works for you.

**Comment by MartijnR** [comment]
Thanks. (This is a great project by the way. Thanks a lot for making this available).

The build now progresses much further (with just `npm install libxslt`). It errors here:

```
==> default:   CXX(target) Release/obj.target/node-libxslt/src/node_libxslt.o
==> default: ../src/node_libxslt.cc:1:0: warning: "BUILDING_NODE_EXTENSION" redefined [enabled by default]
==> default:  #define BUILDING_NODE_EXTENSION
==> default:  ^
==> default: <command-line>:0:0: note: this is the location of the previous definition
==> default: ../src/node_libxslt.cc:5:26: fatal error: libxslt/xslt.h: No such file or directory
==> default:  #include <libxslt/xslt.h>
==> default:                           ^
==> default: compilation terminated.
==> default: make:
==> default: *** [Release/obj.target/node-libxslt/src/node_libxslt.o] Error 1
==> default: make: Leaving directory `/vagrant/node_modules/libxslt/build'
==> default: gyp
==> default:
==> default: ERR!
==> default:
==> default: build error
==> default:
==> default: gyp
==> default:
==> default: ERR!
==> default:
==> default: stack
==> default:  Error: `make` failed with exit code: 2
==> default: gyp
==> default:
==> default: ERR!
==> default:
==> default: stack
==> default:      at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
==> default: gyp
==> default:
==> default: ERR!
==> default:
==> default: stack
==> default:      at ChildProcess.emit (events.js:98:17)
==> default: gyp
==> default:
==> default: ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
==> default: gyp ERR! System Linux 3.13.0-24-generic
==> default: gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
==> default: gyp ERR! cwd /vagrant/node_modules/libxslt
==> default: gyp ERR! node -v v0.10.39
==> default: gyp ERR! node-gyp -v
==> default:  v2.0.1
==> default: gyp ERR! not ok
==> default: npm
==> default:
==> default: ERR!
==> default:  libxslt@0.5.0 install: `node-gyp rebuild`
==> default: npm
==> default:
==> default: ERR!
==> default:  Exit status 1
==> default: npm
==> default:
==> default: ERR!
==> default:
==> default: npm
==> default:
==> default: ERR!
==> default:  Failed at the libxslt@0.5.0 install script.
==> default: npm
==> default:
==> default: ERR!
==> default:  This is most likely a problem with the libxslt package,
==> default: npm
==> default:  ERR! not with npm itself.
==> default: npm ERR! Tell the author that this fails on your system:
==> default: npm ERR!     node-gyp rebuild
==> default: npm ERR! You can get their info via:
==> default: npm ERR!     npm owner ls libxslt
==> default: npm ERR! There is likely additional logging output above.
==> default: npm ERR! System Linux 3.13.0-24-generic
==> default: npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
==> default: npm ERR! cwd /vagrant
==> default: npm ERR! node -v v0.10.39
==> default: npm ERR! npm -v 1.4.28
==> default: npm ERR! code ELIFECYCLE
==> default: npm
==> default:
==> default: ERR!
==> default:
==> default: not ok
==> default:  code 0
```

**Comment by i-like-robots** [comment]
@albanm Thanks for taking a look. Unfortunately I'm still unable to install, I've pasted the output below:

```
> libxmljs@0.14.1 install /Users/matt.hinchliffe/Projects/next-article/node_modules/libxslt/node_modules/libxmljs
> node-gyp rebuild

  CC(target) Release/obj.target/libxml/vendor/libxml/buf.o
  CC(target) Release/obj.target/libxml/vendor/libxml/catalog.o
  CC(target) Release/obj.target/libxml/vendor/libxml/chvalid.o
  CC(target) Release/obj.target/libxml/vendor/libxml/dict.o
  CC(target) Release/obj.target/libxml/vendor/libxml/encoding.o
  CC(target) Release/obj.target/libxml/vendor/libxml/entities.o
  CC(target) Release/obj.target/libxml/vendor/libxml/error.o
  CC(target) Release/obj.target/libxml/vendor/libxml/globals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/hash.o
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLparser.o
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLtree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/legacy.o
  CC(target) Release/obj.target/libxml/vendor/libxml/list.o
  CC(target) Release/obj.target/libxml/vendor/libxml/parser.o
../vendor/libxml/parser.c:13492:43: warning: passing 'const xmlChar *' (aka 'const unsigned char *') to parameter of type 'const char *' converts between
      pointers to integer types with different sign [-Wpointer-sign]
        hdlr = xmlFindCharEncodingHandler(doc->encoding);
                                          ^~~~~~~~~~~~~
../vendor/libxml/include/libxml/encoding.h:175:42: note: passing argument to parameter 'name' here
        xmlFindCharEncodingHandler      (const char *name);
                                                     ^
1 warning generated.
  CC(target) Release/obj.target/libxml/vendor/libxml/parserInternals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/pattern.o
  CC(target) Release/obj.target/libxml/vendor/libxml/relaxng.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX2.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX.o
  CC(target) Release/obj.target/libxml/vendor/libxml/tree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/threads.o
../vendor/libxml/threads.c:442:9: warning: comparison of function 'pthread_mutex_lock' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
    if (pthread_mutex_lock != NULL)
        ^~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:442:9: note: prefix with the address-of operator to silence this warning
    if (pthread_mutex_lock != NULL)
        ^
        &
../vendor/libxml/threads.c:512:9: warning: comparison of function 'pthread_mutex_unlock' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
    if (pthread_mutex_unlock != NULL)
        ^~~~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:512:9: note: prefix with the address-of operator to silence this warning
    if (pthread_mutex_unlock != NULL)
        ^
        &
../vendor/libxml/threads.c:666:33: error: use of undeclared identifier 'xmlOnceInit'
    pthread_once(&once_control, xmlOnceInit);
                                ^
../vendor/libxml/threads.c:670:31: warning: implicit declaration of function 'xmlNewGlobalState' is invalid in C99 [-Wimplicit-function-declaration]
        xmlGlobalState *tsd = xmlNewGlobalState();
                              ^
../vendor/libxml/threads.c:670:25: warning: incompatible integer to pointer conversion initializing 'xmlGlobalState *' (aka 'struct _xmlGlobalState *') with
      an expression of type 'int' [-Wint-conversion]
        xmlGlobalState *tsd = xmlNewGlobalState();
                        ^     ~~~~~~~~~~~~~~~~~~~
../vendor/libxml/threads.c:804:33: error: use of undeclared identifier 'xmlOnceInit'
    pthread_once(&once_control, xmlOnceInit);
                                ^
../vendor/libxml/threads.c:866:14: warning: comparison of function 'pthread_once' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        if ((pthread_once != NULL) &&
             ^~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:866:14: note: prefix with the address-of operator to silence this warning
        if ((pthread_once != NULL) &&
             ^
             &
../vendor/libxml/threads.c:867:14: warning: comparison of function 'pthread_getspecific' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
            (pthread_getspecific != NULL) &&
             ^~~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:867:14: note: prefix with the address-of operator to silence this warning
            (pthread_getspecific != NULL) &&
             ^
             &
../vendor/libxml/threads.c:868:14: warning: comparison of function 'pthread_setspecific' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
            (pthread_setspecific != NULL) &&
             ^~~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:868:14: note: prefix with the address-of operator to silence this warning
            (pthread_setspecific != NULL) &&
             ^
             &
../vendor/libxml/threads.c:869:14: warning: comparison of function 'pthread_key_create' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
            (pthread_key_create != NULL) &&
             ^~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:869:14: note: prefix with the address-of operator to silence this warning
            (pthread_key_create != NULL) &&
             ^
             &
../vendor/libxml/threads.c:870:14: warning: comparison of function 'pthread_key_delete' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
            (pthread_key_delete != NULL) &&
             ^~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:870:14: note: prefix with the address-of operator to silence this warning
            (pthread_key_delete != NULL) &&
             ^
             &
../vendor/libxml/threads.c:871:14: warning: comparison of function 'pthread_mutex_init' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
            (pthread_mutex_init != NULL) &&
             ^~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:871:14: note: prefix with the address-of operator to silence this warning
            (pthread_mutex_init != NULL) &&
             ^
             &
../vendor/libxml/threads.c:872:14: warning: comparison of function 'pthread_mutex_destroy' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
            (pthread_mutex_destroy != NULL) &&
             ^~~~~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:872:14: note: prefix with the address-of operator to silence this warning
            (pthread_mutex_destroy != NULL) &&
             ^
             &
../vendor/libxml/threads.c:873:14: warning: comparison of function 'pthread_mutex_lock' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
            (pthread_mutex_lock != NULL) &&
             ^~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:873:14: note: prefix with the address-of operator to silence this warning
            (pthread_mutex_lock != NULL) &&
             ^
             &
../vendor/libxml/threads.c:874:14: warning: comparison of function 'pthread_mutex_unlock' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
            (pthread_mutex_unlock != NULL) &&
             ^~~~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:874:14: note: prefix with the address-of operator to silence this warning
            (pthread_mutex_unlock != NULL) &&
             ^
             &
../vendor/libxml/threads.c:875:14: warning: comparison of function 'pthread_cond_init' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
            (pthread_cond_init != NULL) &&
             ^~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:875:14: note: prefix with the address-of operator to silence this warning
            (pthread_cond_init != NULL) &&
             ^
             &
../vendor/libxml/threads.c:876:14: warning: comparison of function 'pthread_cond_destroy' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
            (pthread_cond_destroy != NULL) &&
             ^~~~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:876:14: note: prefix with the address-of operator to silence this warning
            (pthread_cond_destroy != NULL) &&
             ^
             &
../vendor/libxml/threads.c:877:14: warning: comparison of function 'pthread_cond_wait' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
            (pthread_cond_wait != NULL) &&
             ^~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:877:14: note: prefix with the address-of operator to silence this warning
            (pthread_cond_wait != NULL) &&
             ^
             &
../vendor/libxml/threads.c:878:14: warning: comparison of function 'pthread_equal' not equal to a null pointer is always true [-Wtautological-pointer-compare]
            (pthread_equal != NULL) &&
             ^~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:878:14: note: prefix with the address-of operator to silence this warning
            (pthread_equal != NULL) &&
             ^
             &
../vendor/libxml/threads.c:879:14: warning: comparison of function 'pthread_self' not equal to a null pointer is always true [-Wtautological-pointer-compare]
            (pthread_self != NULL) &&
             ^~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:879:14: note: prefix with the address-of operator to silence this warning
            (pthread_self != NULL) &&
             ^
             &
../vendor/libxml/threads.c:879:14: note: suffix with parentheses to turn this into a function call
            (pthread_self != NULL) &&
             ^
                         ()
../vendor/libxml/threads.c:880:14: warning: comparison of function 'pthread_cond_signal' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
            (pthread_cond_signal != NULL)) {
             ^~~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:880:14: note: prefix with the address-of operator to silence this warning
            (pthread_cond_signal != NULL)) {
             ^
             &
../vendor/libxml/threads.c:916:35: warning: comparison of function 'pthread_key_delete' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
    if ((libxml_is_threaded)  && (pthread_key_delete != NULL))
                                  ^~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:916:35: note: prefix with the address-of operator to silence this warning
    if ((libxml_is_threaded)  && (pthread_key_delete != NULL))
                                  ^
                                  &
../vendor/libxml/threads.c:918:20: error: expected expression
    once_control = PTHREAD_ONCE_INIT;
                   ^
/usr/include/pthread.h:204:27: note: expanded from macro 'PTHREAD_ONCE_INIT'
#define PTHREAD_ONCE_INIT {_PTHREAD_ONCE_SIG_init, {0}}
                          ^
20 warnings and 3 errors generated.
make: *** [Release/obj.target/libxml/vendor/libxml/threads.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/matt.hinchliffe/.nvm/versions/node/v0.12.5/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/Users/matt.hinchliffe/.nvm/versions/node/v0.12.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/matt.hinchliffe/Projects/next-article/node_modules/libxslt/node_modules/libxmljs
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
```

**Comment by albanm** [comment]
This last one is specific to OS X no ?

I think it might be fixed by this commit from libxmljs: https://github.com/polotek/libxmljs/commit/2409bfec52c8aac5c88f4d229387d537cf41ef75

@gagern could you perhaps merge this commit in your fork ?

**Comment by gagern** [comment]
Merged in https://github.com/polotek/libxmljs/commit/563f72e0e537eb85527e8609fe3b3d8215176f7f. If this continues, I might have to fork libxmljs and see about getting it published on nodejs.org, using a different name.

**Comment by albanm** [comment]
Thanks.

I just published node-libxslt 0.5.1 using your latest commit.

**Comment by MartijnR** [comment]
Oh I get it now.... Because of the git submodule this cannot be installed via npm at the moment, right?

**Comment by gagern** [comment]
Sounds like https://github.com/npm/npm/issues/1876

**Comment by albanm** [comment]
It can not be installed via npm if you have a direct git link in your package.json.

But the git submodule should have no effect at all if you install from a published version (latest being 0.5.1). This is why I cannot recommend users to temporarily use a git url and I had to publish these last few versions while I was hoping to wait a little.

**Comment by MartijnR** [comment]
Thanks. I was using the regular published version (0.5.1). `npm install libxslt` fails for me on node 0.12 (and also node 0.10). 

If you're using vagrant, can you perhaps run this vagrantfile to reproduce? :
```
Vagrant.configure("2") do |config|
  config.vm.box = "trusty"
  config.vm.box_url = "ubuntu/trusty64"
  config.vm.provision "shell", inline: <<-SHELL
  	curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
  	apt-get install -y git build-essential nodejs
  	npm explore npm -g -- npm install node-gyp@latest
  	npm install libxslt
  SHELL
end
```

error:
```
==> default: <command-line>:0:0: note: this is the location of the previous definition
==> default: ../src/node_libxslt.cc:5:26: fatal error: libxslt/xslt.h: No such file or directory
==> default:  #include <libxslt/xslt.h>
==> default:                           ^
==> default: compilation terminated.
==> default: make:
==> default: *** [Release/obj.target/node-libxslt/src/node_libxslt.o] Error 1
==> default: make: Leaving directory `/home/vagrant/node_modules/libxslt/build'
==> default: gyp
==> default:
==> default: ERR!
==> default:
==> default: build error
==> default:
==> default: gyp
==> default:
==> default: ERR!
==> default:
==> default: stack
==> default:  Error: `make` failed with exit code: 2
==> default: gyp
==> default:
==> default: ERR!
==> default:
==> default: stack
==> default:      at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
==> default: gyp
==> default:
==> default: ERR!
==> default:
==> default: stack
==> default:      at ChildProcess.emit (events.js:110:17)
==> default: gyp
==> default:
==> default: ERR!
==> default:
==> default: stack
==> default:      at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
==> default: gyp
==> default:
==> default: ERR! System Linux 3.13.0-24-generic
==> default: gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
==> default: gyp ERR! cwd /home/vagrant/node_modules/libxslt
==> default: gyp ERR! node -v v0.12.6
==> default: gyp ERR! node-gyp -v v2.0.1
==> default: gyp ERR! not ok
==> default: npm
==> default:
==> default: ERR!
==> default:  Linux 3.13.0-24-generic
==> default: npm
==> default:
==> default: ERR!
==> default:
==> default: argv
==> default:  "/usr/bin/node" "/usr/bin/npm" "install" "libxslt"
==> default: npm
==> default:
==> default: ERR!
==> default:
==> default: node
==> default:  v0.12.6
==> default: npm
==> default:
==> default: ERR!
==> default:
==> default: npm
==> default:  v2.11.2
==> default: npm
==> default:
==> default: ERR!
==> default:
==> default: code
==> default:  ELIFECYCLE
==> default: npm
==> default:
==> default: ERR!
==> default:  libxslt@0.5.1 install: `node-gyp rebuild`
==> default: npm
==> default:
==> default: ERR!
==> default:  Exit status 1
==> default: npm
==> default:
==> default: ERR!
==> default:
==> default: npm
==> default:
==> default: ERR!
==> default:  Failed at the libxslt@0.5.1 install script 'node-gyp rebuild'.
==> default: npm
==> default:
==> default: ERR!
==> default:  This is most likely a problem with the libxslt package,
==> default: npm
==> default:
==> default: ERR!
==> default:  not with npm itself.
==> default: npm
==> default:
==> default: ERR!
==> default:  Tell the author that this fails on your system:
==> default: npm
==> default:
==> default: ERR!
==> default:      node-gyp rebuild
==> default: npm
==> default:
==> default: ERR!
==> default:  You can get their info via:
==> default: npm ERR!     npm owner ls libxslt
==> default: npm ERR! There is likely additional logging output above.
==> default: npm
==> default:
==> default: ERR!
==> default:  Please include the following file with any support request:
==> default: npm
==> default:
==> default: ERR!
==> default:      /home/vagrant/npm-debug.log
```

**Comment by gagern** [comment]
Verified on Docker:

```
host$ docker run -t -i ubuntu
# apt-get update
# apt-get install -y curl
# curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
# apt-get install -y git build-essential nodejs python
# npm explore npm -g -- npm install node-gyp@latest
# npm install libxslt
```

Unfortunately `npm` removes all build artifacts after the failure, so I can't see what's going on. But it *did* compile libxslt itself and was just turning to node-libxslt. Strange.

**Comment by MartijnR** [comment]
thanks @gagern 

It seems there is some kind of path set incorrectly `fatal error: libxslt/xslt.h: No such file or directory`.

**Comment by gagern** [comment]
I wonder whether I could only build it on my system because I had libxslt already installed system-wide. Perhaps we're really missing an include path here.

**Comment by MartijnR** [comment]
Thanks! :+1: 

Builds on bare 0.10 and 0.12 with `npm install libxslt` now.
